"""Add support to database for plants

Revision ID: b59e213fe1f6
Revises: 21c84ed53301
Create Date: 2023-08-09 05:06:22.872650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59e213fe1f6'
down_revision = '21c84ed53301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=128), nullable=True),
    sa.Column('sci_name', sa.String(length=128), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_common_name'), ['common_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_plant_sci_name'), ['sci_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_sci_name'))
        batch_op.drop_index(batch_op.f('ix_plant_common_name'))

    op.drop_table('plant')
    # ### end Alembic commands ###
